from __future__ import annotations
from datetime import datetime
from typing import Dict, List, Optional, Protocol
from ..entities import Empleado, Prestamo, RadioFrecuencia, SapUsuario

class EmpleadoRepository(Protocol):
    def obtener_por_cedula(self, cedula: str) -> Optional[Empleado]: ...
    def listar(self, q: Optional[str] = None) -> List[Empleado]: ...
    def crear(self, *, cedula: str, nombre: str, activo: bool = True) -> Empleado: ...
    def actualizar(self, *, cedula: str, cambios: Dict[str, object]) -> Empleado: ...
    def eliminar(self, *, cedula: str) -> None: ...

class RadioRepository(Protocol):
    def obtener_por_codigo(self, codigo: str) -> Optional[RadioFrecuencia]: ...
    def listar(self, q: Optional[str] = None) -> List[RadioFrecuencia]: ...
    def crear(self, *, codigo: str, descripcion: Optional[str] = None, activo: bool = True) -> RadioFrecuencia: ...
    def actualizar(self, *, codigo: str, cambios: Dict[str, object]) -> RadioFrecuencia: ...
    def eliminar(self, *, codigo: str) -> None: ...

class SapUsuarioRepository(Protocol):
    def obtener_por_username(self, username: str) -> Optional[SapUsuario]: ...
    def listar(self, q: Optional[str] = None) -> List[SapUsuario]: ...
    def crear(self, *, username: str, empleado_cedula: Optional[str] = None, activo: bool = True) -> SapUsuario: ...
    def actualizar(self, *, username: str, cambios: Dict[str, object]) -> SapUsuario: ...
    def eliminar(self, *, username: str) -> None: ...

class PrestamoRepository(Protocol):
    def crear(self, prestamo: Prestamo) -> Prestamo: ...
    def obtener_prestamo_abierto(
        self,
        *,
        cedula: Optional[str] = None,
        usuario_sap: Optional[str] = None,
        codigo_radio: Optional[str] = None,
    ) -> Optional[Prestamo]: ...
    def marcar_devolucion(self, id_: int, fecha_hora: datetime) -> Prestamo: ...
    def listar(self, *, cedula: Optional[str] = None, codigo_radio: Optional[str] = None) -> List[Prestamo]: ...
