# Generated by Django 5.2.6 on 2025-09-23 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rf_empleados',
            },
        ),
        migrations.CreateModel(
            name='RadioFrecuenciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=25, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rf_radios',
            },
        ),
        migrations.CreateModel(
            name='SapUsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_sap', to='app.empleadomodel')),
            ],
            options={
                'db_table': 'rf_sap_usuarios',
            },
        ),
        migrations.CreateModel(
            name='PrestamoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_prestamo', models.DateTimeField()),
                ('turno', models.CharField(max_length=40)),
                ('estado', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('DEVUELTO', 'Devuelto')], default='ASIGNADO', max_length=10)),
                ('fecha_hora_devolucion', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='app.empleadomodel')),
                ('usuario_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_registrados', to=settings.AUTH_USER_MODEL)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='app.radiofrecuenciamodel')),
                ('usuario_sap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='app.sapusuariomodel')),
            ],
            options={
                'db_table': 'rf_prestamos',
                'indexes': [models.Index(fields=['radio', 'fecha_hora_devolucion'], name='rf_prestamo_radio_i_9f7857_idx'), models.Index(fields=['empleado', 'fecha_hora_prestamo'], name='rf_prestamo_emplead_43b95a_idx')],
            },
        ),
    ]
