# Generated by Django 5.2.6 on 2025-10-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restructure_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prestamomodel',
            name='prestamos_usuario_registra_idx',
        ),
        migrations.RenameIndex(
            model_name='empleadomodel',
            new_name='empleados_cedula_186ec8_idx',
            old_name='empleados_cedula_idx',
        ),
        migrations.RenameIndex(
            model_name='empleadomodel',
            new_name='empleados_activo_8ab26a_idx',
            old_name='empleados_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='prestamomodel',
            new_name='prestamos_cedula_4ba31e_idx',
            old_name='prestamos_cedula_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='prestamomodel',
            new_name='prestamos_codigo__091710_idx',
            old_name='prestamos_codigo_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='prestamomodel',
            new_name='prestamos_usuario_e36916_idx',
            old_name='prestamos_usuario_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='radiofrecuenciamodel',
            new_name='radios_codigo_182eda_idx',
            old_name='radios_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='radiofrecuenciamodel',
            new_name='radios_activo_95f8d6_idx',
            old_name='radios_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='sapusuariomodel',
            new_name='sap_usuario_usernam_d095d3_idx',
            old_name='sap_usuarios_username_idx',
        ),
        migrations.RenameIndex(
            model_name='sapusuariomodel',
            new_name='sap_usuario_activo_29fc59_idx',
            old_name='sap_usuarios_activo_idx',
        ),
        migrations.AlterField(
            model_name='empleadomodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleadomodel',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prestamomodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radiofrecuenciamodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sapusuariomodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['aggregate', 'action'], name='audit_log_aggrega_797e08_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['at'], name='audit_log_at_1a4cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['actor_user_id'], name='audit_log_actor_u_ae2850_idx'),
        ),
    ]
